algoritmo "sexo"
var

   A, B, C: Inteiro

inicio

      A <- 2
      B <- 3
      C <- 5
      Escreval("Alguns operadores relacionais muito fodas")
      Escreval( A > B )
      Escreval ( A = B )
      Escreval ( A <> B )
      Escreval ( A > 2 )
      Escreval ( A >= 2 )
      Escreval ( C = A+B)
      Escreval ( C >= A+B)
      Escreval ( C >= A^B )
      Escreval ( C <= A^B )
      
fimalgoritmo
